<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>RTcmix - Reference - srand</title>
	
	<link rel="stylesheet" type="text/css" href="/includes/style.css">
	
</head>
<body>
	
<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/head.inc'); ?>


<b>srand</b> - seed the random number generator
</P>
<P>


<HR>
<h3>Synopsis</h3>
<P>
<b>srand</b>([ <i>seed</i> ])
<p>
Parameters inside the [brackets] are optional.
</P>
<P>


<HR>
<h3>Description</h3>
<P>
Call <b>srand</b> to seed RTcmix's built-in random number generator
before using one of the random functions.
<P>
You can call <b>srand</b> more than once in a script, if you want to
restart the random number generator.
<P>
If you don't use <b>srand</b>, RTcmix uses 1 as the random seed.
<P>


<HR>
<h3>Arguments</h3>
<DL>
<DT><A NAME="item_seed"><i>seed</i></A><BR>
<DD>
The seed can be any integer.  Starting with a specific seed causes
a random function to generate the same series of numbers every time
you run the script.  (Though it's possible that different platforms
will give different results from the same script.)
<P>
If not present, then the seed is taken from the system microsecond
counter.  This means that the series of numbers generated by random
functions will be different every time you run the script.
<P></P></DL>


<HR>
<h3>Examples</h3>
<PRE>
   srand(1)
   value = rand()
   print(value)
</PRE>
prints 0.02770996 every time you run the script.
<PRE>
   srand()
   value = rand()
   print(value)
</PRE>
prints a different number every time you run the script, because the
seed is never the same (since it comes from the microsecond counter).
<PRE>
   srand(777)
   for (start = 0; start < 10; start = start + 0.5) {
      frequency = (random() * 200) + 300
      WAVETABLE(start, dur, amp, frequency)
   }
</PRE>
plays a series of notes with frequencies between 300 and 500 Hz.
This series will be the same every time you run the script.
<P>

<HR>
<h3>See Also</h3>
<P>
<A HREF="irand.php">irand</A>,
<A HREF="trand.php">trand</A>,
<A HREF="random.php">random</A>,
<A HREF="rand.php">rand</A>,
<A HREF="pickrand.php">pickrand</A>,
<A HREF="pickwrand.php">pickwrand</A>,
<A HREF="spray_init.php">spray_init</A>,
<A HREF="get_spray.php">get_spray</A>,
<A HREF="maketable.php#random">maketable("random")</A>


<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/foot.inc'); ?>

