<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>RTcmix - Reference - system</title>
	
	<link rel="stylesheet" type="text/css" href="/includes/style.css">
	
</head>
<body>
	
<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/head.inc'); ?>


<b>system</b> - perform any system call
</P>
<P>


<HR>
<h3>Synopsis</h3>
<P><b>system</b>(<i>"command_line"</i>)
</P>
<P>

<HR>
<h3>Description</h3>
<P>
This provides a way to do from an RTcmix script most anything you could
do from a unix shell.  The directory in which the command will execute is
the directory in which RTcmix was invoked.
<p>
NOTE:  This feature is disabled in
<a href="http://rtcmix.org/iRTcmix/">iRTcmix</a>
because of restrictions on iOS apps placed by Apple.
<P>


<HR>
<h3>Arguments</h3>
<DL>
<DT><A NAME="item_command_line"><i>"command_line"</i></A><BR>
<DD>
A double-quoted string giving unix shell command to perform.
<P></P></DL>
<P>


<HR>
<h3>RETURN VALUE</h3>
<P>
The return value of the shell command.
<P>


<HR>
<h3>NOTES</h3>
<P>The call is performed during the initialization portion of an RTcmix
script that contains calls to real-time instruments.  That is, it
happens while RTcmix is parsing the script, but before it has run any
of the instruments called in the script.  This means you can't use
<b>system</b> to opertae upon a sound file generated by instruments in the
script, because the file won't contain anything yet when <b>system</b>
does its work.
<P>


<HR>
<h3>Examples</h3>
<pre>
   system("rm -f pvoctest.aif")
   system("ls -l *.aif")
</pre>
This will remove the file "pvoctest.aif" and then list the contents of the
current working directory.
<p>

<HR>
<h3>See Also</h3>
<p>
<a href="f_arg.php">f_arg</a>,
<a href="i_arg.php">i_arg</a>,
<a href="n_arg.php">n_arg</a>,
<a href="s_arg.php">s_arg</a>,
<a href="include.php">include</a>,
<a href="stringify.php">stringify</a>

<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/foot.inc'); ?>

