<table class="mainnav">
	<tr>
		<td></td>
		<td width="640">
			<a href="/">Home</a> &nbsp;&middot;&nbsp; 
			<a href="/standalone/">Standalone</a> &nbsp;&middot;&nbsp; 
			<a href="/rtcmix~/">rtcmix~</a> &nbsp;&middot;&nbsp; 
			<a href="/irtcmix/">iRTcmix</a> &nbsp;&middot;&nbsp; 
			<a href="/tutorials/">Tutorials</a> &nbsp;&middot;&nbsp; 
			<a href="/reference/">Reference</a>
		</td>
		<td></td>
	</tr>
</table>

<center>

<table class="header">
	<tr>
		<td>
			<a href="/" class="logo">RTcmix</a><br />
			<span class="tagline">an open-source digital signal processing and sound synthesis language</span>
		</td>
		<td valign="bottom" align="right">
			<a href="/about">about</a> &middot; <a href="/links">links</a> &middot; <a href="/contact">contact</a>
		</td>
	</tr>
</table>

<table class="bodycopy">
	<tr>
		<td valign="top">